version: '3.1'

services:
  database:
    container_name: file-fort-postgres
    image: postgres:14.5
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=newPassword
      - POSTGRES_DB=file-fort
    ports:
      - '5447:5432'

  adminer:
    container_name: file-fort-adminer
    image: adminer:4.8.1
    environment:
      ADMINER_DEFAULT_SERVER: postgresql
      ADMINER_DESIGN: hever
    ports:
      - "8080:8080"

  redis:
    container_name: 'file-fort-redis'
    image: redis:6.2-alpine
    ports:
      - "6080:6379"
